n1 = input()
n2 = input()
print(n1)
print(n2)
print(n1, '+', n2, '=', int(n1) + int(n2))
print(n1, '-', n2, '=', int(n1) - int(n2))
print(n1, '*', n2, '=', int(n1) * int(n2))
print(n1, '/', n2, '=', int(n1) / int(n2))
print(n1, '//', n2, '=', int(n1) // int(n2))
print(n1, '%', n2, '=', int(n1) % int(n2))
print(n1, '**', n2, '=', int(n1) ** int(n2))