a = input()
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
# print(a, b, c, d, e, f, g)

na = int(a)
nb = int(b)
nc = int(c)
nd = int(d)
ne = int(e)
nf = int(f)
ng = int(g)
print((na + 2), end=' ')
print((nb - 2), end=' ')
print((nc * 2), end=' ')
print((nd / 2), end=' ')
print((ne // 2), end=' ')
print((nf % 2), end=' ')
print((ng ** 2), end=' ')